version: '3.7'

services:
    mysql:
        image: mysql:8
        container_name: mysql_service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: TianMiao
        volumes:
            - ./MySQL:/docker-entrypoint-initdb.d
    tomcat:
        image: tomcat:9-jre10
        ports:
            - 8080:8080
        volumes:
            - ./TianMiao/target/TianMiao.war:/usr/local/tomcat/webapps/TianMiao.war
        depends_on:
            - mysql
