version: '3.7'

services:
    mysql:
        image: mysql:8
        container_name: mysql_service
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: TianMiao
        ports:
            - 3306:3306
        networks:
            - my-network
        volumes:
            - ./MySQL/:/var/lib/mysql rw
    tomcat:
        image: tomcat:9-jre10
        ports:
            - 8080:8080
        networks:
            - my-network
        volumes:
            - ./TianMeow/target/TianMeow.war:/usr/local/tomcat/webapps/TianMeow.war
        depends_on:
            - mysql
networks:
    my-network:
        driver: bridge
